In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8] # Returns index value

8

In [ ]:
arr[1:5] # Displays from 1 to not 5

In [ ]:
arr[0:5] # Displays from 0 to not 5

In [ ]:
arr[:5] # Displays from start to not 5

In [ ]:
arr[5:] # Displays from 5 to end

In [ ]:
# BROADCASTING

In [6]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
slice_of_arr = arr[0:5] # This points to the original array, meaning whatever changes we made will also affects the original array.
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
arr

In [ ]:
slice_of_arr[:] = 99

In [ ]:
slice_of_arr

In [ ]:
arr

In [9]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100
arr_copy

In [ ]:
arr

In [10]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [11]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape # Returns no. of rows then no. of columns

In [ ]:
arr_2d[0]

In [ ]:
arr_2d[1]

In [ ]:
arr_2d[2]

In [ ]:
arr_2d[0][1]
arr_2d[0,1]

In [12]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr_2d[:2,1:]

In [ ]:
arr_2d[1:][:2]

In [ ]:
# CONDITIONAL SELECTION

In [13]:
arr = np.arange(0,11)

In [ ]:
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr > 4

In [ ]:
arr[arr>4]